import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  grid: {
    flexGrow: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    paddingVertical: 10,
    paddingTop: 0,
    overflow: "visible",
  },
  row: {
    justifyContent: "space-around",
    marginVertical: 5,
  },

  statsPanel: {
    position: "absolute",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    top: 60,
    width: "90%",
    alignSelf: "center",
    zIndex: 1000,
    padding: 10,
    flexWrap: "wrap",
  },
  statsItem: {
    backgroundColor: "#C57CFF",
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 5,
    minWidth: 100,
    flexShrink: 0,
    flexGrow: 0,
    alignItems: "center",
  },
  statsText: {
    color: "#FFF",
    fontSize: 16,
    fontFamily: "FredokaSemiBold",
    textAlign: "center",
  },

  /** ───────── Фиолетовая подсказка (круг) ───────── */
  hintGlowPurple: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#9021E8",
    shadowOpacity: 0.8,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  hintBorderPurple: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 3,
    borderColor: "#C57CFF",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  // градиент полностью заполняет область внутри бордера — без зазора
  hintButtonInnerPurple: {
    width: "100%",
    height: "100%",
    borderRadius: 27,
    justifyContent: "center",
    alignItems: "center",
  },

  /** ───────── Кнопка уровней (пилюля, как на скрине клиента) ───────── */
  difficultyGlow: {
    aspectRatio: 5 / 3,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#9021E8",
    shadowOpacity: 0.8,
    shadowRadius: 25,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  difficultyBorder: {
    width: "100%",
    height: 50,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: "#C57CFF",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  difficultyButton: {
    width: "100%",
    height: "100%",
    borderRadius: 25,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  difficultyTouch: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  difficultyIcon: {
    width: 46,
    height: 46,
    tintColor: "#FFFFFF",
  },

  backButton: {
    position: "absolute",
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: "rgba(18, 18, 18, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    top: 34,
    left: 30,
    zIndex: 1000,
    padding: 8,
  },

  congratsContainer: {
    position: "absolute",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    top: "60%",
    transform: [{ translateY: -100 }],
    zIndex: 3500,
  },
  congratsGlow: {
    position: "absolute",
    width: 50,
    height: 50,
    borderRadius: 125,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
    shadowColor: "#C27CFF",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  congratsFon: {
    width: 344,
    height: 100,
    resizeMode: "contain",
    zIndex: 1,
  },
  congratsText: {
    position: "absolute",
    color: "#FFFFFF",
    fontSize: Math.min(40, width * 0.08),
    fontFamily: "FredokaSemiBold",
    textAlign: "center",
    zIndex: 10,
    textShadowColor: "rgba(197, 124, 255, 0.5)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 5,
  },

  playAgainButton: {
    position: "absolute",
    width: Math.min(200, width * 0.5),
    height: Math.min(68, height * 0.14),
    bottom: height * 0.15,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 3000,
    overflow: "visible",
  },
  playAgainGradient: {
    flex: 1,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "#C57CFF",
    backgroundColor: "#FFC965",
    shadowColor: "#C27CFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  playAgainContent: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  playAgainText: {
    fontFamily: "FredokaSemiBold",
    fontSize: Math.min(16, width * 0.04),
    color: "#C57CFF",
    lineHeight: Math.min(20, width * 0.05),
  },
  playIcon: {
    width: 24,
    height: 24,
    resizeMode: "contain",
  },

  overlay: {
    position: "absolute",
    width: "100%",
    height: "40%",
    bottom: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    zIndex: 10,
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    pointerEvents: "none", // 🔥 КРИТИЧНО
  },

  robotContainer: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 5000,
    elevation: 50,
    width: 130,
    height: 130,
    pointerEvents: "none",
  },
  robotImage: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },

  difficultySmallWrapper: {
    position: "absolute",
    left: 30,
    bottom: 40,
    width: 74,
    height: 74,
    borderRadius: 37,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#9021E8",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  difficultySmallButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#C57CFF",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  difficultySmallIcon: {
    width: 26,
    height: 26,
    tintColor: "#FFFFFF",
    resizeMode: "contain",
  },
});

export default styles;
